#!/bin/bash
#
# Script to create and run docker-glance image.
#
set -x
set -e

# Check for Root user
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root or with sudo"
    exit 1
fi

# Configure the Glance Image Name
export IMAGE_NAME="${IMAGE_NAME:-glance}"

# Configure the Glance Container Name
export CONTAINER_NAME="${CONTAINER_NAME:-glance}"

# Configure the Glance Hostname
export HOSTNAME="${HOSTNAME:-$HOSTNAME}"

# Configure the Glance Hostname
export DNS_SEARCH="${DNS_SEARCH:-example.com}"

docker run --privileged -d -h $HOSTNAME --dns-search $DNS_SEARCH -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 9191:9191 -p 9292:9292 --name="$CONTAINER_NAME" $IMAGE_NAME

# Get the PID of the Glance Container
CONTAINER_PID="$(docker inspect --format={{.State.Pid}} $CONTAINER_NAME)"

#Use nsenter to enter the namespaces of the running Glance container.
nsenter -m -u -n -i -p -t $CONTAINER_PID /bin/bash

exit $?
